'use client';

export default function Terms() {
  return (
    <main className="min-h-screen bg-[#0A0A0A] selection:bg-white/[0.08] selection:text-[#EDEDED] py-24 px-6 sm:px-12">
      <article className="max-w-3xl mx-auto">
        <header className="mb-16 border-b border-white/[0.08] pb-10">
          <h1 className="text-[#EDEDED] text-4xl md:text-5xl font-semibold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-[#71717A] text-sm uppercase tracking-widest">
            Last Updated: July 8, 2026
          </p>
        </header>

        <div className="space-y-12">
          
          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed">
              By accessing or using the Parlexa directory and marketplace at parlexa.in (the "Service"), you agree to be bound by these Terms of Service. If you are using the Service on behalf of an organization, you agree to these Terms on behalf of that organization and represent that you have the authority to do so.
            </p>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              2. Description of Service
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed mb-4">
              Parlexa is an enterprise-grade directory and marketplace for Artificial Intelligence agents and tools. We provide a platform for vendors to list their software and for users to discover, compare, and save these tools.
            </p>
            <ul className="list-none space-y-3 pl-4 border-l border-white/[0.08]">
              <li className="text-[#A1A1AA] leading-relaxed">
                <strong className="text-[#EDEDED] font-semibold">Third-Party Independence:</strong> Parlexa does not develop, own, or maintain the third-party AI tools listed on the platform. Any interaction, subscription, or data exchange between a user and a third-party vendor is strictly between those two parties.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              3. Vendor Submissions and Account Security
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed mb-6">
              Vendors utilizing Parlexa to list their tools are subject to strict moderation and security protocols enforced by our architecture.
            </p>

            <div className="space-y-8">
              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">
                  3.1 Approval and Moderation
                </h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  All submitted tools are subject to administrative review. Parlexa reserves the right to reject or remove any tool that violates our standards, contains malicious intent, or provides inaccurate descriptions.
                </p>
              </div>

              <div className="bg-white/[0.02] border border-white/[0.08] rounded-lg p-6">
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">
                  3.2 The Security Override Protocol
                </h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  To maintain platform integrity and prevent unauthorized link swapping, <strong className="text-[#EDEDED]">any modification to an already approved listing will automatically revert the tool's status to pending</strong>. The listing will temporarily be removed from the global directory until the changes are re-verified by a Parlexa administrator.
                </p>
              </div>

              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">
                  3.3 Sandboxed Vendor Data
                </h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  Vendors are granted access to an isolated dashboard governed by Row Level Security (RLS). Vendors may only access interaction metrics (such as Top-of-Funnel clicks and High-Intent leads) directly generated by their specific listings.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              4. Acceptable Use and Anti-Spam Protections
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed mb-6">
              You agree not to misuse the Parlexa platform or assist anyone else in doing so.
            </p>
            <ul className="list-none space-y-4 pl-4 border-l border-white/[0.08]">
              <li className="text-[#A1A1AA] leading-relaxed">
                <strong className="text-[#EDEDED] font-semibold">Automated Interactions:</strong> Parlexa utilizes zero-latency analytics logging alongside client-side request throttling (2000ms execution locks). Any attempt to bypass these locks or artificially inflate tracking metrics is strictly prohibited.
              </li>
              <li className="text-[#A1A1AA] leading-relaxed">
                <strong className="text-[#EDEDED] font-semibold">Prohibited Conduct:</strong> Users and Vendors shall not attempt to breach the Supabase backend architecture, submit malicious tools, or scrape the directory via automated endpoints.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              5. Intellectual Property
            </h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">5.1 Parlexa IP</h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  The platform's proprietary code, backend architecture, analytics tracking methodologies, and visual design system ("Silicon Valley Dark" aesthetic, including all UI layouts and CSS structural elements) are the exclusive intellectual property of Parlexa.
                </p>
              </div>
              
              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">5.2 Vendor IP</h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  Vendors retain all intellectual property rights to their individual AI tools, submitted logos, and brand descriptions. By submitting a tool, vendors grant Parlexa a worldwide, royalty-free license to display their logos, generated screenshots, and descriptions on the platform and in promotional materials.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              6. Disclaimers and Limitation of Liability
            </h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">6.1 "As Is" Provision</h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  The Service is provided on an "as is" and "as available" basis. Parlexa makes no warranties, express or implied, regarding the availability, uptime, or absolute security of the platform, nor do we guarantee the functionality or safety of any third-party tool listed in our directory.
                </p>
              </div>
              
              <div>
                <h3 className="text-[#EDEDED] text-xl font-semibold tracking-tight mb-3">6.2 Liability Cap</h3>
                <p className="text-[#A1A1AA] leading-relaxed">
                  To the maximum extent permitted by law, Parlexa shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the Service or any third-party tool found via the Service.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              7. Governing Law and Dispute Resolution
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of India. Any legal actions or proceedings arising out of or relating to these Terms or the use of the Parlexa platform shall be brought exclusively in the courts located in Ahmedabad, Gujarat, and you hereby consent to the personal jurisdiction of such courts.
            </p>
          </section>

          <section>
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              8. Modifications to Terms
            </h2>
            <p className="text-[#A1A1AA] leading-relaxed">
              Parlexa reserves the right to modify these Terms at any time. Material changes will be communicated via platform notifications or direct email to registered vendors. Continued use of the Service after changes are published constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section className="pt-12 mt-12 border-t border-white/[0.08]">
            <h2 className="text-[#EDEDED] text-2xl font-semibold tracking-tight mb-4">
              9. Contact Information
            </h2>
            <div className="flex flex-col space-y-2">
              <p className="text-[#A1A1AA] leading-relaxed flex items-center">
                <span className="text-[#71717A] uppercase tracking-widest text-xs w-24">Email</span>
                <a href="mailto:legal@parlexa.in" className="text-[#EDEDED] hover:text-white transition-colors duration-300">
                  legal@parlexa.in
                </a>
              </p>
              <p className="text-[#A1A1AA] leading-relaxed flex items-center">
                <span className="text-[#71717A] uppercase tracking-widest text-xs w-24">Website</span>
                <a href="https://parlexa.in" className="text-[#EDEDED] hover:text-white transition-colors duration-300">
                  parlexa.in
                </a>
              </p>
            </div>
          </section>

        </div>
      </article>
    </main>
  );
}
